#!/bin/bash

# Request autorun to generate the list of nodes so that we can kill.
# The list can be in any order.
#
# Do not overwrite the nodemap previously generated by run-all.sh
autorun_gen_nodes=1
overwrite_nodemap=0
source $(dirname $0)/autorun.sh

for node in $autorun_nodes; do
	blue "Killing node-$node"
	ssh -oStrictHostKeyChecking=no $node "cd hots/app/$autorun_app/; ./kill.sh" &
done

wait
