#!/bin/bash

# We need the node list, but don't overwrite the nodemap generated by run-all.sh
autorun_gen_nodes=1
overwrite_nodemap=0
source $(dirname $0)/autorun.sh

# Process the output of each machine in /tmp/$autorun_logdir.
# Prints per-machine and average throughput

#
# Copy per-machine outputs to $autorun_combined_logdir
#
rm -rf $autorun_combined_logdir
mkdir $autorun_combined_logdir

for node in $autorun_nodes; do
	echo "Fetching output of $node"

	# We don't have the node ID to HoTS machine ID mapping here, so use the
	# remote filename as the target filename
	scp $node:$autorun_logdir/out* $autorun_combined_logdir/ \
		1>/dev/null 2>/dev/null &
done
wait

#
# Process the accumulated output files
#
for filename in $autorun_combined_logdir/*; do
	# Print a machine's output. Do not use the most recent output since it
	# may be affected by the scp
	machine_tput_string=`tail -1000 $filename | \
		grep "Machine commit tput" | tail -6 | head -1`
	echo $filename " " $machine_tput_string

	# Assemble a string with each machine's throughput
	machine_tput_double=`echo $machine_tput_string | cut -d' ' -f 5`
	tputs_string=$tputs_string" "$machine_tput_double

	num_machines=`expr $num_machines + 1`
done

echo "tputs_string: $tputs_string"

# Take the average of the combined throughput string
avg_tput=`echo $tputs_string | awk '{
	s = 0; \
	for(i = 1; i <= NF; i++) \
		s += $i; \
	print s / NF; \
	}'`

echo "Average throughput ($num_machines) machines = $avg_tput M/s"
