#!/bin/bash
# Process the output of each machine in /tmp/$autorun_app

source $(dirname $0)/utils.sh

# We need the node list, but don't overwrite the nodemap generated by run-all.sh
autorun_gen_nodes=1
overwrite_nodemap=0
source $(dirname $0)/autorun.sh

# Temporary directory for storing scp-ed files
tmpdir="/tmp/${autorun_app}_proc"
rm -rf $tmpdir
mkdir $tmpdir

node_index=0
for node in $autorun_nodes; do
  # Keeping destination file name = node name helps in debugging.
	echo "proc-out: Fetching $autorun_stat_file from $node to $tmpdir/$node"
  scp $node:$autorun_stat_file $tmpdir/$node \
		1>/dev/null 2>/dev/null &

  ((node_index+=1))
done
wait
echo "proc-out: Finished fetching files."

num_columns=`cat $tmpdir/* | head -1 | wc -w`
echo "proc-out: Detected $num_columns columns"

# Process the accumulated output files. This assumes that the files have
# space-separated numbers in columns.

tot_rows="0" # Total rows processed, for rolling average
avg[0]="" # Per-column average
for col in `seq 1 $num_columns`; do
  avg[$col]="0.0"
done

for filename in $tmpdir/*; do
  echo "proc-out: Processing file $filename."

  # Ignore files with less than 12 lines
  lines_in_file=`cat $filename | wc -l`
  if [ $lines_in_file -le 12 ]; then
    blue "proc-out: Ignoring $filename. Too short ($lines_in_file lines), 12 required."
    continue;
  fi

  # Cut out the first 6 and last 6 lines into compute_temp - use this for stats
  awk -v nr="$(wc -l < $filename)" 'NR > 6 && NR < (nr - 6)' $filename > proc_out_tmp
  remaining_rows=`cat proc_out_tmp | wc -l`

  for col in `seq 1 $num_columns`; do
    file_avg=`awk -v col=$col '{ total += $col } END { printf "%.3f", total / NR  }' proc_out_tmp`
    prev_sum=`echo "scale=3; ${avg[$col]} * $tot_rows" | bc -l`
    cur_sum=`echo "scale=3; $file_avg * $remaining_rows" | bc -l`
    avg[$col]=`echo "scale=3; ($prev_sum + $cur_sum) / ($tot_rows + $remaining_rows)" | bc -l`
    echo "proc-out: Column $col average for $filename = $file_avg. Current running average = ${avg[$col]}"
  done

  ((tot_rows+=$remaining_rows))
done

for col in `seq 1 $num_columns`; do
  blue "proc-out: Final column $col average = ${avg[$col]}"
done

rm -f proc_out_tmp
